title: Kensaku
description: >-
  A WordPress package to search Entities including Rest API Endpoints and React Components
url: "https://spaghetti-dojo.github.io/kensaku"
baseurl: "/kensaku"

remote_theme: just-the-docs/just-the-docs

aux_links:
  "Kensaku on Github":
    - "https://github.com/spaghetti-dojo/kensaku"

aux_links_new_tab: true

nav_external_links:
  - title: Go to the Repository
    url: https://github.com/spaghetti-dojo/kensaku
    opens_in_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

toc:
  enabled: true
  h_min: 1
  h_max: 3

plugins:
  - jekyll-remote-theme
