title: Wp Entities Search
description: >-
  A WordPress package to search Entities including Rest API Endpoints and React Components
url: 'https://widoz.github.io/wp-entities-search'
baseurl: '/wp-entities-search'

toc:
  enabled: true
  h_min: 1
  h_max: 3

remote_theme: sighingnow/jekyll-gitbook

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
