title: Wp Entities Search
description: >-
  A WordPress package to search Entities including Rest API Endpoints and React Components
url: 'https://widoz.github.io/wp-entities-search'
baseurl: '/wp-entities-search'

remote_theme: riggraz/no-style-please

toc:
  enabled: true
  h_min: 1
  h_max: 3

plugins:
  - jekyll-remote-theme
