name: Assets Artifacts

on:
  workflow_dispatch:

  create:
    types: [tag]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Assets
        uses: ./github/actions/assets-artifacts
        with:
          build-command: 'yarn build'
