name: Assets Artifacts

on:
  workflow_dispatch:

  push:
    branches:
      - 'feature/16/github-actions-artifacts'

  create:
    types: [tag]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!github.event.commits[0].message.match(/--skip-assets-artifacts/)"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install
        run: yarn install

      - name: Build Assets
        uses: ./.github/actions/assets-artifacts
