name: Assets Artifacts

on:
  create:
    types: [tag]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run custom action
        uses: ./github/actions/assets-artifacts
        with:
          build-command: 'yarn build'
