name: Client Linting

on:
  workflow_dispatch: { }

  pull_request:

  push:
    branches:
      - main

    paths:
      - '**/workflows/client-linting.yml'
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!github.event.pull_request.draft"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pnpm Install
        uses: pnpm/action-setup@v4
        with:
          version: '^9'
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Linting JavaScript
        run: pnpm run lint:js

      - name: Unit Tests
        run: pnpm run test
