name: JS Quality Assurance
on:
  pull_request:
    types: [ assigned, opened, reopened, ready_for_review, synchronize ]
  push:
    branches:
      - main
      - feature/post-types-select
    paths:
      - '**/workflows/*js*'
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.json'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        run: yarn install

      - name: QA
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: yarn lint:js
